### ISSUE TITLE
user-agent

### ISSUE THREAD

**Issue by bjuergens** [jernejovc/pystreamable#1]
Please add the ability to set a custom user-agent.

According  to the docs, streamable wants a user-agent for bots. 

> Usage of the API requires a Streamable account and valid email. All requests must be authenticated with Basic Auth. **If you're a bot, please provide a descriptive user agent as well.**

https://streamable.com/documentation

If I read it correctly this lib has no way to specify a custom user-agent, and also doesn't set any user agent at all.

**Comment by bjuergens** [comment]
this looks easy: http://docs.python-requests.org/en/master/user/quickstart/#custom-headers

I might even do this myself (... if I have time)

**Comment by jernejovc** [comment]
Hi, thanks for pointing this out, currently there is no option to specify user agent, and the user agent is not set. I'll add the user-agent, but no ability to override or disable it for now.

**Comment by jernejovc** [comment]
I've just uploaded version 1.0.1 to pypi that sends the user-agent HTTP header, you can upgrade using pip. I'll close this issue, please reopen or create a new one if something's not right :)
