### ISSUE TITLE
ChunkedEncodingError when uploading video

### ISSUE THREAD

**Issue by bjuergens** [jernejovc/pystreamable#2]
My script stopped uploading videos about 2 months ago. 

here is a minimal example for the error:

```python
>>> from pystreamable import StreamableApi
>>> import secret
>>> client_streamable = StreamableApi(secret.streamable_user, secret.streamable_pass)
>>> locale_file_name="data/working/my_file.mp4"
>>> client_streamable.upload_video(locale_file_name, 'my video')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pystreamable/StreamableApi.py", line 72, in upload_video
    files=files)
  File "/usr/local/lib/python2.7/dist-packages/pystreamable/StreamableApi.py", line 114, in _api_request
    headers=USER_AGENT)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 658, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
>>> 
```

It would be a big help if I knew if this issue only affects me, or others, too

**Comment by jernejovc** [comment]
Hi, sorry for getting back to you so late.
I've tested the example with python3 and python2 and can't seem to reproduce the issue.
Maybe the requests library has some issues (old version maybe?). In my tests I was using 2.18.4 (python3) and 2.9.1 (python2).

**Comment by bjuergens** [comment]
Thanks, this got me on the right track:  My Account got banned. 

When I tried to login (via the website), I got: 

> Your account has been suspended for violating our Terms of Service. If you believe this was done in error, please contact us at support@streamable.com.

**Comment by jernejovc** [comment]
Ah, that might be an issue, yes. One thing that's not in README and you can try before uploading is to check the user info (https://github.com/jernejovc/pystreamable/blob/master/pystreamable/StreamableApi.py#L85).

I would be curious what the API response is in the case of a banned account (403 vs. json with some error code vs. something else..).

**Comment by bjuergens** [comment]
> I would be curious what the API response is in the case of a banned account

easy! 

just upload some "violent" or "nsfw" videos from reddit and report yourself. 

> One thing that's not in README and you can try before uploading is to check the user info (

That's a good idea. I will definitely do this in the future.
