### ISSUE TITLE
pystreamable.exceptions.StreamableApiServerException is now triggered on any instance of upload

### ISSUE THREAD

**Issue by MahdeenSky** [jernejovc/pystreamable#4]
I have been using this wrapper for a good while, but now this error just pops up, and honestly I don't know why it happens.

pystreamable.exceptions.StreamableApiServerException

**Comment by jernejovc** [comment]
Hi,
I'll try to reproduce the issue in the following days.

**Comment by MahdeenSky** [comment]
Alright so i found out why it happens, apparently if the account you're using got suspended/banned, then you will receive this error. Guess maybe a pull request, for this specific error would be nice, as im sure im not the only one who'll have to deal with this in the future considering the automation of uploading videos, some potentially breaking TOS.

**Comment by jernejovc** [comment]
Nice catch, in this case we would need to improve error handling for these cases, since at least the case where account may be suspended could be useful to handle (also handle any possible api throttling, if present).

**Comment by jernejovc** [comment]
If you are able to provide error handling implementation for at least the cases of suspended/banned accounts since you have an account like that on hand that would be greatly appreciated.
